name: Build Container Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_push:
    name: Build & Push
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: |
          ghcr.io/${{ github.repository }},enable=true
        flavor: |
          latest=auto
        tags: |
          type=sha
          type=ref,event=pr
          type=raw,value=${{ needs.rust_version.outputs.rust_version }},enable={{is_default_branch}}

    - uses: earthly/actions-setup@v1.0.2

    - name: Login to ghcr.io
      uses: docker/login-action@v2
      if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Push container image
      env:
        EARTHLY_PUSH: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        EARTHLY_REMOTE_CACHE: ghcr.io/sksat/cargo-chef-docker:cache-${{ matrix.base_img }}-${{ matrix.arch }}
      run: |
        earthly +docker \
          --DOCKER_META_VERSION=${{ steps.meta.outputs.version }}
