name: Build Container Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_push:
    name: Build & Push
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base_tag: [bookworm, bookworm-slim, bullseye, bullseye-slim, buster, buster-slim, experimental, stable, stable-slim, testing, testing-slim, unstable, unstable-slim]

    steps:
    - uses: actions/checkout@v3

    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: |
          ghcr.io/${{ github.repository }},enable=true
        flavor: |
          latest=auto
        tags: |
          type=sha
          type=ref,event=pr
          type=raw,value=${{ needs.rust_version.outputs.rust_version }},enable={{is_default_branch}}

    - uses: earthly/actions-setup@v1.0.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to ghcr.io
      uses: docker/login-action@v2
      if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Push container image
      env:
        EARTHLY_PUSH: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        EARTHLY_REMOTE_CACHE: ghcr.io/${{ github.repository }}:cache-${{ matrix.base_tag }}-${{ matrix.arch }}
      run: |
        earthly +docker \
         --BASE_TAG=${{ matrix.base_tag }}  --DOCKER_META_VERSION=${{ steps.meta.outputs.version }}
